package database

import (
	"fmt"

	"gorm.io/gorm"
)

// ModelRepository handles LLM model registry operations.
//
// The registry mixes two kinds of rows:
//   - base models      (owner_id IS NULL) — visible to every user.
//   - finetuned models (owner_id = user)  — only the owner sees them.
//
// Visibility is enforced in GetAvailableModels and CheckAccess; callers in
// handlers don't need to repeat the predicate.
type ModelRepository struct {
	db *DB
}

func NewModelRepository(db *DB) *ModelRepository {
	return &ModelRepository{db: db}
}

// Create inserts a new model row. ID is generated by BeforeCreate if empty.
func (r *ModelRepository) Create(m *Model) (*Model, error) {
	if err := r.db.Conn.Create(m).Error; err != nil {
		return nil, fmt.Errorf("failed to create model: %w", err)
	}
	return m, nil
}

// GetByID returns the model regardless of ownership. Use CheckAccess before
// exposing the result to a user.
func (r *ModelRepository) GetByID(id string) (*Model, error) {
	var m Model
	err := r.db.Conn.Where("id = ?", id).First(&m).Error
	if err == gorm.ErrRecordNotFound {
		return nil, fmt.Errorf("model not found")
	}
	if err != nil {
		return nil, fmt.Errorf("failed to get model: %w", err)
	}
	return &m, nil
}

// GetAvailableModels returns the list visible to userID: every base model
// plus the user's own finetuned models. Order: base first (so the dropdown
// shows shared models above per-user ones), then by created_at desc.
func (r *ModelRepository) GetAvailableModels(userID string) ([]Model, error) {
	var models []Model
	err := r.db.Conn.
		Where("type = ? OR (type = ? AND owner_id = ?)", "base", "finetuned", userID).
		Order("type ASC, created_at DESC").
		Find(&models).Error
	if err != nil {
		return nil, fmt.Errorf("failed to list models: %w", err)
	}
	return models, nil
}

// CheckAccess returns true if userID is allowed to assign this model to a
// bot (or otherwise act on it). Base models are world-readable; finetuned
// models are owner-only.
func (r *ModelRepository) CheckAccess(modelID, userID string) (bool, *Model, error) {
	m, err := r.GetByID(modelID)
	if err != nil {
		return false, nil, err
	}
	if m.Type == "base" {
		return true, m, nil
	}
	if m.OwnerID == nil || *m.OwnerID != userID {
		return false, m, nil
	}
	return true, m, nil
}

// GetAll returns every model row regardless of ownership. Used at boot
// for reconcile() so we can stop tracking containers that no longer exist
// — visibility checks happen elsewhere, this is an admin-grade read.
func (r *ModelRepository) GetAll() ([]Model, error) {
	var models []Model
	if err := r.db.Conn.Order("created_at DESC").Find(&models).Error; err != nil {
		return nil, fmt.Errorf("failed to list all models: %w", err)
	}
	return models, nil
}

// FindByFilePath looks up a model by its on-disk path. Used by the seed-on-start
// flow to avoid duplicate base-model rows when files have already been registered.
func (r *ModelRepository) FindByFilePath(filePath string) (*Model, error) {
	var m Model
	err := r.db.Conn.Where("file_path = ?", filePath).First(&m).Error
	if err == gorm.ErrRecordNotFound {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("failed to find model by path: %w", err)
	}
	return &m, nil
}

// Update persists changes to an existing model row. Uses Select("*") + Omit
// so zero-value fields (e.g. ContainerPort = 0 after stop) do get written.
func (r *ModelRepository) Update(m *Model) error {
	result := r.db.Conn.Model(m).
		Where("id = ?", m.ID).
		Select("*").
		Omit("id", "created_at").
		Updates(m)
	if result.Error != nil {
		return fmt.Errorf("failed to update model: %w", result.Error)
	}
	if result.RowsAffected == 0 {
		return fmt.Errorf("model not found")
	}
	return nil
}

// Delete removes a finetuned model. Refuses to delete base models so a buggy
// admin click can't destroy the platform default. Bot rows referencing this
// model fall back to the default endpoint via ON DELETE SET NULL on the FK.
func (r *ModelRepository) Delete(modelID, userID string) error {
	var m Model
	if err := r.db.Conn.Where("id = ?", modelID).First(&m).Error; err != nil {
		if err == gorm.ErrRecordNotFound {
			return fmt.Errorf("model not found")
		}
		return fmt.Errorf("failed to get model: %w", err)
	}
	if m.Type == "base" {
		return fmt.Errorf("cannot delete base model")
	}
	if m.OwnerID == nil || *m.OwnerID != userID {
		return fmt.Errorf("not allowed")
	}

	// Detach bots that reference this model so DELETE doesn't fail on the FK.
	r.db.Conn.Exec("UPDATE bots SET model_id = NULL WHERE model_id = ?", modelID)

	if err := r.db.Conn.Delete(&Model{}, "id = ?", modelID).Error; err != nil {
		return fmt.Errorf("failed to delete model: %w", err)
	}
	return nil
}
